# Graph data for all the Traveling Ethiopia problems

# Figure 1: Basic state space graph (no costs, no heuristics)
FIGURE_1_GRAPH = {
    'Addis Ababa': ['Ambo', 'Debre Birhan', 'Adama', 'Wolkite'],
    'Adama': ['Addis Ababa', 'Matahara', 'Batu', 'Assella'],
    'Adigrat': ['Adwa', 'Mekelle'],
    'Adwa': ['Shire', 'Axum', 'Adigrat'],
    'Alamat': ['Mekelle', 'Woldia', 'Fanti Rasu', 'Samara'],
    'Ambo': ['Debre Markos', 'Nekemete', 'Addis Ababa'],
    'Arba Minch': ['Dawro', 'Konso'],
    'Assasa': ['Shashemene', 'Dodolla', 'Goba'],
    'Assella': ['Batu', 'Adama', 'Dodolla'],
    'Assosa': ['Metekel', 'Dembi Dollo'],
    'Awash': ['Matahara', 'Samara', 'Gabi Rasu', 'Chiro'],
    'Axum': ['Shire', 'Adwa'],
    'Babile': ['Harar', 'Jigjiga'],
    'Bahir Dar': ['Azezo', 'Debre Tabor', 'Injibar', 'Finote Selam'],
    'Bale': ['Dodolla', 'Goba', 'Sof Oumer'],
    'Basketo': ['Mezan Teferi', 'Dawro', 'Bench Maji', 'Konso'],
    'Batu': ['Buta Jirra', 'Adama', 'Assella', 'Shashemene'],
    'Bedelle': ['Nekemete', 'Gore', 'Jimma'],
    'Bench Maji': ['Basketo', 'Juba'],
    'Bonga': ['Tepi', 'Jimma', 'Mezan Teferi', 'Dawro'],
    'Bule Hora': ['Dilla', 'Yabello'],
    'Buta Jirra': ['Wolkite', 'Batu'],
    'Chiro': ['Awash', 'Dire Dawa'],
    'Dawro': ['Bonga', 'Wolaita Sodo', 'Basketo', 'Arba Minch'],
    'Debarke': ['Shire', 'Gondar'],
    'Debre Birhan': ['Debre Sina', 'Addis Ababa'],
    'Debre Markos': ['Finote Selam', 'Ambo'],
    'Debre Sina': ['Kemise', 'Debre Birhan'],
    'Debre Tabor': ['Gondar', 'Bahir Dar', 'Woldia'],
    'Dega Habur': ['Jigjiga', 'Goba', 'Kebri Dehar'],
    'Dembi Dollo': ['Assosa', 'Gimbi'],
    'Dessie': ['Woldia', 'Kemise'],
    'Dilla': ['Hawassa', 'Bule Hora'],
    'Dire Dawa': ['Chiro', 'Harar'],
    'Dodolla': ['Assella', 'Assasa', 'Bale', 'Liben'],
    'Dollo': ['Gode', 'Mokadisho'],
    'Fanti Rasu': ['Alamat', 'Kilbet Rasu'],
    'Finote Selam': ['Bahir Dar', 'Debre Markos'],
    'Gabi Rasu': ['Samara', 'Awash'],
    'Gambella': ['Gore', 'Juba'],
    'Gimbi': ['Nekemete', 'Dembi Dollo'],
    'Goba': ['Assasa', 'Bale', 'Sof Oumer', 'Dega Habur'],
    'Gode': ['Kebri Dehar', 'Dollo'],
    'Gondar': ['Debarke', 'Azezo', 'Debre Tabor'],
    'Gore': ['Bedelle', 'Gambella', 'Tepi'],
    'Harar': ['Dire Dawa', 'Babile'],
    'Hawassa': ['Wolaita Sodo', 'Shashemene', 'Dilla'],
    'Hossana': ['Jimma', 'Worabe', 'Wolaita Sodo'],
    'Humer': ['Metem', 'Shire'],
    'Injibar': ['Bahir Dar', 'Metekel'],
    'Jigjiga': ['Babile', 'Dega Habur'],
    'Jimma': ['Bedelle', 'Wolkite', 'Hossana', 'Bonga'],
    'Kebri Dehar': ['Sof Oumer', 'Dega Habur', 'Gode', 'Werder'],
    'Kemise': ['Dessie', 'Debre Sina'],
    'Kilbet Rasu': ['Fanti Rasu'],
    'Konso': ['Basketo', 'Arba Minch', 'Yabello'],
    'Lalibela': ['Sekota', 'Woldia'],
    'Liben': ['Dodolla', 'Moyale'],
    'Matahara': ['Adama', 'Awash'],
    'Mekelle': ['Adigrat', 'Sekota', 'Alamat'],
    'Metekel': ['Injibar', 'Assosa'],
    'Metem': ['Kartum', 'Humer', 'Azezo'],
    'Mezan Teferi': ['Bonga', 'Basketo'],
    'Moyale': ['Yabello', 'Liben', 'Nairobi'],
    'Nekemete': ['Ambo', 'Gimbi', 'Bedelle'],
    'Samara': ['Alamat', 'Gabi Rasu', 'Awash'],
    'Sekota': ['Mekelle', 'Lalibela'],
    'Shashemene': ['Worabe', 'Batu', 'Hawassa', 'Assasa'],
    'Shire': ['Humer', 'Adwa', 'Axum', 'Debarke'],
    'Sof Oumer': ['Bale', 'Goba', 'Kebri Dehar'],
    'Tepi': ['Gore', 'Bonga'],
    'Werder': ['Kebri Dehar'],
    'Woldia': ['Lalibela', 'Debre Tabor', 'Alamat', 'Dessie'],
    'Wolaita Sodo': ['Hossana', 'Dawro', 'Hawassa'],
    'Wolkite': ['Addis Ababa', 'Jimma', 'Buta Jirra', 'Worabe'],
    'Worabe': ['Wolkite', 'Hossana', 'Shashemene'],
    'Yabello': ['Konso', 'Bule Hora', 'Moyale'],
}

# Helper to make the graph bidirectional
def make_bidirectional(graph):
    """Turns a one-way graph into bidirectional."""
    bidirectional = {}
    for node, neighbors in graph.items():
        if node not in bidirectional:
            bidirectional[node] = {}
        for neighbor, cost in neighbors.items():
            # Add forward edge
            bidirectional[node][neighbor] = cost
            # Add backward edge
            if neighbor not in bidirectional:
                bidirectional[neighbor] = {}
            bidirectional[neighbor][node] = cost
    return bidirectional

# Figure 2: State space graph with backward costs (one-way definitions)
FIGURE_2_GRAPH_ONE_WAY = {
    'Kartum': {'Humer': 21, 'Metem': 19},
    'Humer': {'Shire': 8, 'Debarke': 9, 'Metem': 7},
    'Shire': {'Adwa': 2, 'Axum': 4, 'Debarke': 7},
    'Adwa': {'Asmera': 5, 'Mekelle': 4},
    'Axum': {'Mekelle': 7},
    'Debarke': {'Gondar': 6},
    'Metem': {'Azezo': 7},
    'Gondar': {'Azezo': 4, 'Bahir Dar': 7},
    'Azezo': {'Bahir Dar': 4},
    'Mekelle': {'Kilbet Rasu': 6, 'Sekota': 5, 'Alamat': 9},
    'Kilbet Rasu': {'Fanti Rasu': 7},
    'Sekota': {'Debre Tabor': 8, 'Alamat': 6, 'Lalibela': 8},
    'Fanti Rasu': {'Samara': 11},
    'Alamat': {'Woldia': 7, 'Samara': 8},
    'Bahir Dar': {'Debre Tabor': 4, 'Meteke': 11, 'Injibara': 6, 'Finote Selam': 2},
    'Debre Tabor': {'Woldia': 8},
    'Woldia': {'Dessie': 6, 'Samara': 8},
    'Samara': {'Gabi Rasu': 9},
    'Meteke': {'Injibara': 4},
    'Injibara': {'Finote Selam': 6},
    'Finote Selam': {'Debre Marko': 3},
    'Lalibela': {'Dessie': 4},
    'Dessie': {'Kemise': 4},
    'Gabi Rasu': {'Awash': 5},
    'Kemise': {'Debre Sina': 6},
    'Assosa': {'Dembi Dollo': 12, 'Gimbi': 4},
    'Dembi Dollo': {'Nekemete': 6},
    'Gimbi': {'Nekemete': 9},
    'Nekemete': {'Ambo': 9, 'Bedelle': 7},
    'Ambo': {'Addis Ababa': 5, 'Wolkite': 6},
    'Addis Ababa': {'Debre Birhan': 5, 'Matahara': 3, 'Adama': 4},
    'Debre Birhan': {'Awash': 1},
    'Awash': {'Chiro': 4, 'Dire Dawa': 8},
    'Chiro': {'Harar': 2},
    'Dire Dawa': {'Harar': 4},
    'Harar': {'Babile': 3, 'Goba': 28},
    'Babile': {'Jigjiga': 3},
    'Jigjiga': {'Dega Habur': 5},
    'Dega Habur': {'Kebri Dehar': 6},
    'Kebri Dehar': {'Werder': 6, 'Gode': 5},
    'Gode': {'Dollo': 17, 'Mokadisho': 22, 'Sof Oumer': 23},
    'Matahara': {'Adama': 3},
    'Adama': {'Buta Jirra': 4, 'Batu': 4, 'Assella': 4},
    'Buta Jirra': {'Wolkite': 2, 'Worabe': 2},
    'Wolkite': {'Jimma': 8, 'Hossan': 5},
    'Bedelle': {'Jimma': 7, 'Gore': 6},
    'Gore': {'Tepi': 9, 'Gambella': 5},
    'Gambella': {'Tepi': 4},
    'Tepi': {'Mezan Teferi': 8, 'Bonga': 4},
    'Mezan Teferi': {'Bonga': 4},
    'Bonga': {'Jimma': 4, 'Dawro': 10},
    'Jimma': {'Hossan': 4},
    'Hossan': {'Worabe': 7, 'Wolaita Sodo': 4, 'Shashemene': 7},
    'Worabe': {'Shashemene': 3},
    'Shashemene': {'Assasa': 3, 'Hawassa': 1, 'Dodolla': 13},
    'Assasa': {'Dodolla': 18},
    'Batu': {'Assella': 3},
    'Wolaita Sodo': {'Dawro': 6, 'Hawassa': 3, 'Konso': 4, 'Arba Minch': 5},
    'Dawro': {'Bench Maji': 10, 'Arba Minch': 8},
    'Arba Minch': {'Dawro': 8, 'Wolaita Sodo': 5, 'Konso': 6},
    'Bench Maji': {'Basket': 5, 'Juba': 22},
    'Hawassa': {'Dilla': 3},
    'Dilla': {'Bule Hora': 4},
    'Bule Hora': {'Konso': 3},
    'Konso': {'Yabello': 3},
    'Yabello': {'Moyale': 6},
    'Moyale': {'Nairobi': 22},
    'Dodolla': {'Bale': 13},
    'Bale': {'Liben': 11, 'Goba': 18},
    'Goba': {'Sof Oumer': 6},
}

# Make Figure 2 graph bidirectional
FIGURE_2_GRAPH = make_bidirectional(FIGURE_2_GRAPH_ONE_WAY)

# Figure 3: State space with heuristic values and backward cost
FIGURE_3_HEURISTICS = {
    'Addis Ababa': 26, 'Moyale': 0, 'Ambo': 31, 'Debre Birhan': 31, 'Adama': 23,
    'Wolkite': 25, 'Matahara': 20, 'Buta Jirra': 25, 'Batu': 22, 'Assella': 20,
    'Worabe': 24, 'Hossana': 23, 'Hossan': 23, 'Shashemene': 22, 'Hawassa': 21, 'Dilla': 18,
    'Bule Hora': 15, 'Konso': 12, 'Yabello': 6, 'Liben': 9, 'Dodolla': 18,
    'Assasa': 19, 'Bale': 15, 'Goba': 17, 'Sof Oumer': 14, 'Kebri Dehar': 16,
    'Dega Habur': 19, 'Jigjiga': 20, 'Babile': 21, 'Harar': 22, 'Dire Dawa': 24,
    'Chiro': 26, 'Awash': 27, 'Debre Sina': 32, 'Kemise': 36, 'Dessie': 40,
    'Woldia': 46, 'Lalibela': 57, 'Sekota': 59, 'Alamat': 52, 'Samara': 44,
    'Gabi Rasu': 49, 'Fanti Rasu': 60, 'Kilbet Rasu': 67, 'Mekelle': 61,
    'Adigrat': 65, 'Adwa': 63, 'Axum': 59, 'Shire': 55, 'Humer': 63,
    'Debarke': 62, 'Gondar': 56, 'Azezo': 55, 'Bahir Dar': 48, 'Debre Tabor': 52,
    'Finote Selam': 50, 'Debre Marko': 53, 'Debre Markos': 53, 'Injibara': 54, 'Meteke': 59,
    'Nekemete': 40, 'Gimbi': 49, 'Dembi Dollo': 61, 'Assosa': 73,
    'Bedelle': 33, 'Gore': 39, 'Gambella': 44, 'Tepi': 43, 'Mezan Teferi': 47,
    'Bonga': 39, 'Jimma': 29, 'Wolaita Sodo': 25, 'Dawro': 35, 'Bench Maji': 45,
    'Basket': 50, 'Juba': 72, 'Nairobi': 22, 'Kartum': 81, 'Asmera': 68,
    'Metem': 70, 'Mokadisho': 40, 'Dollo': 33, 'Gode': 21, 'Werder': 22,
    'Arba Minch': 25  # Added for Question 2.3
}

# Figure 3 graph with costs (same as Figure 2 structure, bidirectional)
FIGURE_3_GRAPH = FIGURE_2_GRAPH.copy()

# Figure 4: Adversarial search graph
FIGURE_4_GRAPH = {
    'Addis Ababa': ['Ambo', 'Buta Jirra', 'Adama'],
    'Ambo': ['Gedo', 'Nekemte'],
    'Gedo': ['Shambu', 'Fincha'],
    'Nekemte': ['Gimbi', 'Limu'],
    'Buta Jirra': ['Worabe', 'Wolkite'],
    'Worabe': ['Hossana', 'Durame'],
    'Wolkite': ['Bench Naji', 'Tepi', 'Kaffa'],
    'Adama': ['Mojo', 'Diredawa'],
    'Mojo': ['Dilla'],
    'Diredawa': ['Harar', 'Chiro'],
}

FIGURE_4_UTILITIES = {
    'Shambu': 4,
    'Fincha': 5,
    'Gimbi': 8,
    'Limu': 8,
    'Hossana': 6,
    'Durame': 5,
    'Bench Naji': 5,
    'Tepi': 6,
    'Kaffa': 7,
    'Dilla': 9,
    'Chiro': 6,
    'Harar': 10,
}

# Figure 5: Relaxed state space graph (for ROS/Gazebo)
FIGURE_5_GRAPH = {
    'Dembi Dollo': ['Gambella', 'Gimbi'],
    'Gambella': ['Dembi Dollo', 'Gore'],
    'Gimbi': ['Dembi Dollo', 'Nekemete'],
    'Nekemete': ['Gimbi', 'Bedelle', 'Ambo'],
    'Gore': ['Gambella', 'Tepi', 'Bedelle'],
    'Tepi': ['Gore', 'Bonga', 'Mezan Teferi'],
    'Bedelle': ['Nekemete', 'Gore', 'Jimma', 'Wolkite'],
    'Mezan Teferi': ['Tepi', 'Dawro'],
    'Bonga': ['Tepi', 'Jimma', 'Dawro'],
    'Jimma': ['Bedelle', 'Bonga', 'Worabe'],
    'Ambo': ['Nekemete', 'Addis Ababa', 'Wolkite'],
    'Addis Ababa': ['Ambo', 'Adama', 'Debre Birhan', 'Matahara'],
    'Wolkite': ['Bedelle', 'Ambo', 'Buta Jirra', 'Worabe'],
    'Buta Jirra': ['Wolkite', 'Adama'],
    'Worabe': ['Jimma', 'Wolkite', 'Hossana', 'Shashemene'],
    'Hossana': ['Worabe', 'Wolaita Sodo', 'Shashemene'],
    'Dawro': ['Bonga', 'Mezan Teferi', 'Wolaita Sodo'],
    'Wolaita Sodo': ['Hossana', 'Dawro', 'Hawassa'],
    'Hawassa': ['Wolaita Sodo', 'Dilla', 'Shashemene'],
    'Dilla': ['Hawassa'],
    'Shashemene': ['Worabe', 'Hossana', 'Hawassa', 'Batu', 'Dodolla'],
    'Batu': ['Shashemene', 'Adama', 'Assella'],
    'Adama': ['Buta Jirra', 'Batu', 'Addis Ababa', 'Matahara', 'Assella'],
    'Assella': ['Batu', 'Adama', 'Assasa'],
    'Assasa': ['Assella', 'Dodolla'],
    'Dodolla': ['Shashemene', 'Assasa', 'Bale', 'Goba'],
    'Debre Birhan': ['Addis Ababa', 'Chiro'],
    'Chiro': ['Debre Birhan', 'Awash', 'Dire Dawa'],
    'Awash': ['Matahara', 'Chiro'],
    'Matahara': ['Adama', 'Addis Ababa', 'Awash', 'Dire Dawa'],
    'Dire Dawa': ['Matahara', 'Chiro', 'Harar'],
    'Harar': ['Dire Dawa', 'Babile'],
    'Babile': ['Harar', 'Jigjiga'],
    'Jigjiga': ['Babile', 'Dega Habur'],
    'Dega Habur': ['Jigjiga', 'Kebri Dehar'],
    'Kebri Dehar': ['Dega Habur', 'Gode', 'Goba'],
    'Gode': ['Kebri Dehar'],
    'Goba': ['Dodolla', 'Bale', 'Kebri Dehar'],
    'Bale': ['Dodolla', 'Goba', 'Sof Oumer'],
    'Sof Oumer': ['Bale'],
}

